// Network security group rules for the subnet that an API Management instance of the
// **classic** Developer or Premium tier is injected into.
//
// These live here rather than inline in a network module for the same reason the runner rules
// and the Private DNS zone catalog do: they are reviewed configuration rather than topology,
// and a spoke is generic by design - its subnets are supplied as data - so the rule set has to
// be data too rather than be duplicated into every spoke that hosts API Management.
//
// Unlike most subnets, this rule set is not optional. The load balancer API Management uses
// internally is secure by default and rejects all inbound traffic, so classic injection
// requires an NSG that explicitly allows the control plane in. Without the port 3443 rule the
// instance deploys and then degrades: the Azure portal reports it as unreachable, policy and
// certificate updates stop applying, and platform patches stop arriving. That failure appears
// hours after a green deployment, which is why the rules are declared up front here rather
// than added once something breaks.
//
// The rules follow the "Configure NSG rules" table in "Deploy your Azure API Management
// instance to a virtual network - internal mode", restricted to the rows marked
// **External & Internal**. The external-only rows - Internet inbound on 80 and 443, and
// AzureTrafficManager inbound on 443 - are deliberately omitted: this is an internal-mode
// instance with no public ingress. Adding external mode means adding those rows.
//
// Several of these are already permitted by the Azure platform default rules, which allow all
// outbound and all inbound from `VirtualNetwork` and `AzureLoadBalancer`. They are stated
// explicitly anyway so the instance keeps working if a deny-all rule is introduced later,
// which is the same convention `runner-nsg-rules.bicep` follows.
//
// Priorities start at 200. The spoke module generates its own Bastion rule at priority 100,
// and a collision is an Azure deployment error rather than a build error.
//
// Azure rejects a security rule description longer than 140 characters at preflight with
// `SecurityRuleDescriptionTooLong`, which `az bicep build` does not catch. Keep every
// description below that limit.

import { subnetSecurityRuleType } from 'types.bicep'

@export()
@description('Returns the network security group rules required by a classic Developer or Premium tier API Management instance injected into a virtual network in internal mode. Rules occupy priorities 200 to 250, leaving 100 to 199 for rules generated by the network module and 300 and above for callers. The v2 tiers have different requirements and do not use this rule set.')
func apimSecurityRules() subnetSecurityRuleType[] => [
  {
    name: 'AllowApiManagementManagementEndpointInbound'
    properties: {
      description: 'Control plane reaches the management endpoint. Without this the instance degrades: no portal access, no policy or certificate updates.'
      access: 'Allow'
      direction: 'Inbound'
      priority: 200
      protocol: 'Tcp'
      sourceAddressPrefix: 'ApiManagement'
      sourcePortRange: '*'
      destinationAddressPrefix: 'VirtualNetwork'
      destinationPortRange: '3443'
    }
  }
  {
    name: 'AllowAzureLoadBalancerInbound'
    properties: {
      description: 'Azure infrastructure load balancer health probes on 6390.'
      access: 'Allow'
      direction: 'Inbound'
      priority: 210
      protocol: 'Tcp'
      sourceAddressPrefix: 'AzureLoadBalancer'
      sourcePortRange: '*'
      destinationAddressPrefix: 'VirtualNetwork'
      destinationPortRange: '6390'
    }
  }
  {
    name: 'AllowStorageOutbound'
    properties: {
      description: 'Azure Storage dependency for core service functionality.'
      access: 'Allow'
      direction: 'Outbound'
      priority: 200
      protocol: 'Tcp'
      sourceAddressPrefix: 'VirtualNetwork'
      sourcePortRange: '*'
      destinationAddressPrefix: 'Storage'
      destinationPortRange: '443'
    }
  }
  {
    name: 'AllowSqlOutbound'
    properties: {
      description: 'Azure SQL dependency for core service functionality.'
      access: 'Allow'
      direction: 'Outbound'
      priority: 210
      protocol: 'Tcp'
      sourceAddressPrefix: 'VirtualNetwork'
      sourcePortRange: '*'
      destinationAddressPrefix: 'Sql'
      destinationPortRange: '1433'
    }
  }
  {
    name: 'AllowAzureKeyVaultOutbound'
    properties: {
      description: 'Azure Key Vault dependency for core service functionality, including named values and custom domain certificates.'
      access: 'Allow'
      direction: 'Outbound'
      priority: 220
      protocol: 'Tcp'
      sourceAddressPrefix: 'VirtualNetwork'
      sourcePortRange: '*'
      destinationAddressPrefix: 'AzureKeyVault'
      destinationPortRange: '443'
    }
  }
  {
    name: 'AllowAzureMonitorOutbound'
    properties: {
      description: 'Publish diagnostic logs, metrics, Resource Health and Application Insights telemetry.'
      access: 'Allow'
      direction: 'Outbound'
      priority: 230
      protocol: 'Tcp'
      sourceAddressPrefix: 'VirtualNetwork'
      sourcePortRange: '*'
      destinationAddressPrefix: 'AzureMonitor'
      destinationPortRanges: [
        '443'
        '1886'
      ]
    }
  }
  {
    name: 'AllowCertificateValidationOutbound'
    properties: {
      description: 'Certificate revocation checks for Microsoft-managed and customer-managed certificates. CRL and OCSP endpoints are plain port 80 by design.'
      access: 'Allow'
      direction: 'Outbound'
      priority: 240
      protocol: 'Tcp'
      sourceAddressPrefix: 'VirtualNetwork'
      sourcePortRange: '*'
      destinationAddressPrefix: 'Internet'
      destinationPortRange: '80'
    }
  }
  {
    name: 'AllowAzurePlatformDnsOutbound'
    properties: {
      description: 'Azure DNS at 168.63.129.16, which resolves the private endpoints in this estate. Denying it breaks name resolution for the whole instance.'
      access: 'Allow'
      direction: 'Outbound'
      priority: 250
      protocol: '*'
      sourceAddressPrefix: 'VirtualNetwork'
      sourcePortRange: '*'
      destinationAddressPrefix: '168.63.129.16'
      destinationPortRange: '53'
    }
  }
]
