// Network security group rules for the subnet that hosts the Azure Container Apps environment
// running the self-hosted GitHub Actions runners.
//
// These live here rather than inline in a network module because they are reviewed
// configuration rather than topology, the same way infra/zones.bicep holds the Private DNS
// zone catalog. The runners subnet moved from the hub to a workload spoke, and a spoke is
// generic by design - its subnets are supplied as data - so the rule set had to become data
// too rather than be duplicated into every spoke that hosts runners.
//
// The outbound rules follow "Network security groups for configuring a virtual network in
// Azure Container Apps" for a workload profile environment. They are stated explicitly so the
// environment keeps working if a deny-all rule is introduced later. No deny rule is added
// here: the Azure platform default rules already block inbound from the internet.
//
// Priorities start at 200. The spoke module generates its own Bastion rule at priority 100,
// and a collision is an Azure deployment error rather than a build error.
//
// Azure rejects a security rule description longer than 140 characters at preflight with
// `SecurityRuleDescriptionTooLong`, which `az bicep build` does not catch. Keep every
// description below that limit.

import { subnetSecurityRuleType } from 'types.bicep'

@export()
@description('Returns the network security group rules required by an Azure Container Apps workload profile environment hosting self-hosted GitHub Actions runners, for a subnet with the given address prefix. Rules occupy priorities 200 to 290, leaving 100 to 199 for rules generated by the network module and 300 and above for callers.')
func runnerSecurityRules(subnetAddressPrefix string) subnetSecurityRuleType[] => [
  {
    name: 'AllowContainerAppsSubnetInbound'
    properties: {
      description: 'Communication between addresses inside the Container Apps subnet.'
      access: 'Allow'
      direction: 'Inbound'
      priority: 200
      protocol: '*'
      sourceAddressPrefix: subnetAddressPrefix
      sourcePortRange: '*'
      destinationAddressPrefix: subnetAddressPrefix
      destinationPortRange: '*'
    }
  }
  {
    name: 'AllowAzureLoadBalancerProbeInbound'
    properties: {
      description: 'Azure Load Balancer probes the Container Apps backend pools.'
      access: 'Allow'
      direction: 'Inbound'
      priority: 210
      protocol: 'Tcp'
      sourceAddressPrefix: 'AzureLoadBalancer'
      sourcePortRange: '*'
      destinationAddressPrefix: subnetAddressPrefix
      destinationPortRange: '30000-32767'
    }
  }
  {
    name: 'AllowContainerAppsSubnetOutbound'
    properties: {
      description: 'Communication between addresses inside the Container Apps subnet.'
      access: 'Allow'
      direction: 'Outbound'
      priority: 200
      protocol: '*'
      sourceAddressPrefix: subnetAddressPrefix
      sourcePortRange: '*'
      destinationAddressPrefix: subnetAddressPrefix
      destinationPortRange: '*'
    }
  }
  {
    name: 'AllowMicrosoftContainerRegistryOutbound'
    properties: {
      description: 'Microsoft Artifact Registry, which serves the Container Apps system containers.'
      access: 'Allow'
      direction: 'Outbound'
      priority: 210
      protocol: 'Tcp'
      sourceAddressPrefix: subnetAddressPrefix
      sourcePortRange: '*'
      destinationAddressPrefix: 'MicrosoftContainerRegistry'
      destinationPortRange: '443'
    }
  }
  {
    name: 'AllowAzureFrontDoorFirstPartyOutbound'
    properties: {
      description: 'Dependency of the MicrosoftContainerRegistry service tag.'
      access: 'Allow'
      direction: 'Outbound'
      priority: 220
      protocol: 'Tcp'
      sourceAddressPrefix: subnetAddressPrefix
      sourcePortRange: '*'
      destinationAddressPrefix: 'AzureFrontDoor.FirstParty'
      destinationPortRange: '443'
    }
  }
  {
    name: 'AllowAzureActiveDirectoryOutbound'
    properties: {
      description: 'Managed identity token acquisition, including the federated identity a runner job uses.'
      access: 'Allow'
      direction: 'Outbound'
      priority: 230
      protocol: 'Tcp'
      sourceAddressPrefix: subnetAddressPrefix
      sourcePortRange: '*'
      destinationAddressPrefix: 'AzureActiveDirectory'
      destinationPortRange: '443'
    }
  }
  {
    name: 'AllowAzureMonitorOutbound'
    properties: {
      description: 'Container Apps diagnostics to Azure Monitor.'
      access: 'Allow'
      direction: 'Outbound'
      priority: 240
      protocol: 'Tcp'
      sourceAddressPrefix: subnetAddressPrefix
      sourcePortRange: '*'
      destinationAddressPrefix: 'AzureMonitor'
      destinationPortRange: '443'
    }
  }
  {
    name: 'AllowAzureContainerRegistryOutbound'
    properties: {
      description: 'Pull runner images from Azure Container Registry, reached through a private endpoint in another spoke.'
      access: 'Allow'
      direction: 'Outbound'
      priority: 250
      protocol: 'Tcp'
      sourceAddressPrefix: subnetAddressPrefix
      sourcePortRange: '*'
      destinationAddressPrefix: 'AzureContainerRegistry'
      destinationPortRange: '443'
    }
  }
  {
    name: 'AllowAzureKeyVaultOutbound'
    properties: {
      description: 'Read the GitHub App private key from Key Vault through a private endpoint in another spoke.'
      access: 'Allow'
      direction: 'Outbound'
      priority: 260
      protocol: 'Tcp'
      sourceAddressPrefix: subnetAddressPrefix
      sourcePortRange: '*'
      destinationAddressPrefix: 'AzureKeyVault'
      destinationPortRange: '443'
    }
  }
  {
    name: 'AllowAzurePlatformDnsOutbound'
    properties: {
      description: 'Azure DNS at 168.63.129.16. Container Apps does not function if this is denied.'
      access: 'Allow'
      direction: 'Outbound'
      priority: 270
      protocol: '*'
      sourceAddressPrefix: subnetAddressPrefix
      sourcePortRange: '*'
      destinationAddressPrefix: '168.63.129.16'
      destinationPortRange: '53'
    }
  }
  {
    name: 'AllowGitHubHttpsOutbound'
    properties: {
      description: 'Runners poll GitHub and download actions and packages over HTTPS, through the hub firewall.'
      access: 'Allow'
      direction: 'Outbound'
      priority: 280
      protocol: 'Tcp'
      sourceAddressPrefix: subnetAddressPrefix
      sourcePortRange: '*'
      destinationAddressPrefix: 'Internet'
      destinationPortRange: '443'
    }
  }
]
